
import time
time.clock = time.time
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer

# Create a new chat bot named Charlie
chatbot = ChatBot('Charlie', logic_adapters=[
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.TimeLogicAdapter',
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'qdefault_response': 'I am sorry. I am still learning!',
            'maximum_similarity_threshold': 0.90
        }
    ])

trainer = ListTrainer(chatbot.storage)
# trainer2 = ChatterBotCorpusTrainer(chatbot)

trainer.train([
    'hi',
    "Hi, can I help you?",
    'hi!',
    "Hi, can I help you?",
    'hello',
    "Hi, can I help you?",
    "Hello, how are you?",
    'hi',
    "Hi, can I help you?",
    'hi!',
    "Hi, can I help you?",
    'hello',
    "Hi, can I help you?",
    "Hello, how are you?",
    'hi',
    "Hi, can I help you?",
    'hi!',
    "Hi, can I help you?",
    'hello',
    "Hi, can I help you?",
    "Hello, how are you?",
    'hi',
    "Hi, can I help you?",
    'hi!',
    "Hi, can I help you?",
    'hello',
    "Hi, can I help you?",
    "Hello, how are you?",
    'Hello, charlie',
    'Hello, how can I help you?'
    "I'm fine, thanks for asking. How can I help you?",
    'how are you?',
    "I'm fine, thanks for asking. How can I help you?",
    'I would like info about the rooms',
    'We have three kinds of rooms available, Principal Suites, Family suit, and comofortable. Do you wanna know the prices?',
    'I want info about the rooms',
    'We have three kinds of rooms available, Principal Suites, Family suit, and comofortable. Do you wanna know the prices?',
    'What type of rooms do you have avialble',
    'We have three kinds of rooms available, Principal Suites, Family suit, and comofortable. Do you wanna know the prices?',
    'tell me about the rooms',
    'We have three kinds of rooms available, Principal Suites, Family suit, and comofortable. Do you wanna know the prices?',
    'what kind of rooms do you have',
    'We have three kinds of rooms available, Principal Suites, Family suit, and comofortable. Do you wanna know the prices?',
    'yes',
    'The prices are: Principal Suites, $80 per night; Family suit, $40 y Comofortable, $20',
    'tell me the prices',
    'The prices are: Principal Suites, $80 per night; Family suit, $40 y Comofortable, $20',
    'what are the prices',
    'The prices are: Principal Suites, $80 per night; Family suit, $40 y Comofortable, $20',
    'how much for a room',
    'The prices are: Principal Suites, $80 per night; Family suit, $40 y Comofortable, $20',
    'how much does a room cost',
    'The prices are: Principal Suites, $80 per night; Family suit, $40 y Comofortable, $20',
    'What are the prices of the room',
    'The prices are: Principal Suites, $80 per night; Family suit, $40 y Comofortable, $20',
    'how much does a principal suit cost',
    'it has a price of $80 per night',
    'I do',
    'can you help me',
    'yes, i do. Ask me about the rooms',
    'The prices are: Principal Suites, $80 per night; Family suit, $40 y Comofortable, $20',
    'Yes, I do',
    'The prices are: Principal Suites, $80 per night; Family suit, $40 y Comofortable, $20',
    'What benefits do they include',
    'They include free breakfast',
    'Where are you located',
    'We are located in Caracas, Venezuela. Close to Altamira',
    'What does the principal suit includes',
    'They include 2 rooms, a vestier, 2 bathrooms and a private living room',
    'What does the Family suit includes',
    'They include 4 rooms, 2 bathrooms and a small kitchen and living room',
    'What does the comfortable room includes',
    'It includes a single bed and small bathroom',
    'what time is check in',
    'check in is at 11:00am'
    'hola',
    'hola, como estas?',
    'bien y tu?'
    'bien, gracias por preguntar, como puedo ayudarte?',
    'Quiero informacion acerca de las habitaciones',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'cuentame sobre las habitaciones',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'dime sobre las habitaciones',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'que habitaciones tienen disponible',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'Quiero informacion sobre de las habitaciones',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'Me das informacion sobre las habitaciones',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'Quiero informacion acerca de las habitaciones, por favor',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'Que precio tienen las las habitaciones',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'Cuanto salen las habitaciones',
    'Tenemos 3 tipos de habitaciones disponibles, Suites principales, familiares y comodas, quieres saber los precios?',
    'Dame informacion sobre las suites principales',
    'LAs suites principales son espaciosas, incluyen una sala privada, vestidor, cocina y 2 habitaciones',
    'que incluye la habitacion principal',
    'Las suites principales son espaciosas, incluyen una sala privada, vestidor, cocina y 2 habitaciones',
    'Que incluye la habitacion familiar',
    'incluye 4 habitaciones, 2 baños, una cocina pequeña y una sala pequeña',
    'que incluye la habitacion comoda',
    'Incluye una cama y un baño',
    'si',
    'Los precios son: Principal Suites, $80; Family suit $40 y comodos $20',
    'Cuales son los precios',
    'que precios tienen',
    'Los precios son: Principal Suites, $80; Family suit $40 y comodos $20',
    'Donde se ubican',
    'Nos ubicamos en Caracas, cerca de la plaza altamira',
    'Aceptan niños',
    'Si, aceptamos niños y mascotas',
    'aceptan mascotas',
    'Si, aceptamos mascotas',
    'Tienen desayuno gratis',
    'si, tenemos desayunos gratis',
    'a que hora es el check-in',
    'el check-in es a las 11:00am',
    'can i bring pets',
    'yes, you can. Pets are allowed',
    'puedo llevar a mi mascota',
    'si, aceptamos mascotas',
    'puedo llevar a mi perro',
    'si, aceptamos mascotas'
])

trainer.train([
    'hi',
    'Hello, how can I help you',
    'Hi',
    'Hello, how can I help you',
    'Hello',
    'Hello, how can I help you',
    'hello',
    'How can I help you?',
    'hi',
    'Nice to talk to you. How can I help you?',
    'Thanks',
    'Thanks to you',
    'Thank you',
    'Thanks to you!',
    'I want to book a room',
    'For bookings, call this number: +582121234567',
    'How can I book a room',
    'For bookings, call this number: +582121234567',
    'What is the process for booking a room online?',
    'For bookings, call this number: +582121234567','For bookings, call this number: +582121234567',
    'I would like to reserve a room for two nights. How can I do that?',
    'For bookings, call this number: +582121234567',
    'Can you please help me book a room at your hotel?',
    'For bookings, call this number: +582121234567',
    'How can I check the availability and rates of your rooms?',
    'For bookings, call this number: +582121234567',
    'What are the steps for booking a room through your website?',
    'For bookings, call this number: +582121234567',
    "I'm interested in booking a room for next weekend. How can I proceed?",
    'For bookings, call this number: +582121234567',
    'How can I confirm my reservation for a room at your hotel?',
    'For bookings, call this number: +582121234567',
    'How can I pay for my room booking?',
    'For bookings, call this number: +582121234567',
    'How can I cancel or modify my room booking?',
    'For bookings, call this number: +582121234567',
    'How can I book a room with a specific view or amenity?',
    'For bookings, call this number: +582121234567',
    'How can I book a room for a group or an event?',
    'For bookings, call this number: +582121234567',
    'How can I book a room using a discount code or a voucher?',
    'For bookings, call this number: +582121234567',
    'How can I book a room with special requests or needs?',
    'For bookings, call this number: +582121234567',
    'How can I book a room as a member of your loyalty program?',
    'For bookings, call this number: +582121234567',
    'How can I book a room that includes breakfast or other services?',
    'For bookings, call this number: +582121234567',
    'How can I book a room in advance or at the last minute?',
    'For bookings, call this number: +582121234567',
    'How can I book a room for a long-term stay or a short-term stay?',
    'For bookings, call this number: +582121234567',
    'How can I book a room with flexible or non-refundable cancellation policies?',
    'For bookings, call this number: +582121234567',
    'How can I book a room that is pet-friendly or smoke-free?',
    'For bookings, call this number: +582121234567',
    'How can I book a room that is accessible or has extra space?',
    'Do you have rooms available on',
    'For bookings, call this number: +582121234567',
    'I want to book a room for my anniversary',
    'For bookings, call this number: +582121234567',
    'cuanto cuesta la suit principal',
    'la suit principal tiene un costo de $80 por noche',
    'cuanto cuesta la habitacion familiar',
    'la habitacion familiar tiene un costo de $40 por noche',
    'cuanto cuesta la habitacion comoda',
    'la habitacion comoda tiene un costo de $20 por noche',
    'tienen piscina?'
    'si tenemos piscina',
    'el hotel tiene piscina',
    'si tenemos piscina',
    'hay piscina disponible',
    'si tenemos piscina',

    'hay piscina',
    'si hay piscina',
    'do you have a pool',
    'yes we do have a pool',
    'what does the hotel includes',
    'We have a pool, a restaurant, a gym, and we are located in a good zone',
    'What benefits do they include',
    'We have a pool, a restaurant, a gym, and we are located in a good zone',
    'what benefits does the hotel includes',
    'We have a pool, a restaurant, a gym, and we are located in a good zone',
    'what benefits does the hotel has',
    'We have a pool, a restaurant, a gym, and we are located in a good zone',
    'what benefits does the hotel have',
    'We have a pool, a restaurant, a gym, and we are located in a good zone',
    'que tiene el hotel',
    'El hotel tiene gimnasio, restaurante, piscina y nos ubicamos en una buena zona de caracas',
    'que beneficios tiene el hotel',
    'El hotel tiene gimnasio, restaurante, piscina y nos ubicamos en una buena zona de caracas',

])

trainer.train([
    'hola',
    'Hola. Como puedo ayudarte?',
    'como estas?',
    'bien y tu',
    'bien y tu?',
    'Muy bien, gracias por preguntar. Como puedo ayudarte?',
    'hi',
    'how can I help you?',
    'hi',
    'how can I help you?',
    'hi',
    'how can I help you?',
    'hi',
    'how can I help you?',
    'Hello',
    'how can I help you?',
    'Hi',
    'Do you want info about the rooms?'
])

trainer.train([
    'Quisiera reservar',
    'Para reservar llama al numero +582129054670',
    'como puedo reservar',
    'Para reservar llama al numero +582129054670',
    'Donde puedo reservar',
    'Para reservar llama al numero +582129054670',
    'Tienes un numero donde pueda llamar para reservar',
    'Para reservar llama al numero +582129054670',
    'quiero reservar una habitacion',
    'Para reservar llama al numero +582129054670',
    'Gracias',
    'Gracias a ti.',
    'Muchas gracias',
    'Muchas gracias a ti',
    '¿Cuál es el proceso para reservar una habitación en línea?',
    'Para reservar llama al numero +582129054670',
    'Como puedo reservar una habitacion',
    'Para reservar llama al numero +582129054670',  
    '¿como puedo reservar una habitacion?'
    'Para reservar llama al numero +582129054670',  
    'Me gustaría reservar una habitación por dos noches. ¿Cómo puedo hacer eso?',
    'Para reservar llama al numero +582129054670',
    '¿Puede ayudarme a reservar una habitación en su hotel?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo consultar la disponibilidad y las tarifas de sus habitaciones?',
    'Para reservar llama al numero +582129054670',
    '¿Cuáles son los pasos para reservar una habitación a través de su sitio web?',
    'Para reservar llama al numero +582129054670',
    'Estoy interesado en reservar una habitación para el próximo fin de semana. ¿Cómo puedo proceder?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo confirmar mi reserva de una habitación en su hotel?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo pagar mi reserva de habitación?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo cancelar o modificar mi reserva de habitación?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación con una vista o comodidad específica?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación para un grupo o un evento?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación usando un código de descuento o un cupón?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación con solicitudes o necesidades especiales?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación como miembro de su programa de fidelidad?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación que incluya desayuno u otros servicios?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación con anticipación o en el último minuto?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación para una estadía larga o corta?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación con políticas de cancelación flexibles o no reembolsables?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación que admita mascotas o que sea libre de humo?',
    'Para reservar llama al numero +582129054670',
    '¿Cómo puedo reservar una habitación que sea accesible o que tenga espacio extra?',
    'Para reservar llama al numero +582129054670',
    'Tiene habitaciones disponible',
    'Si tenemos, para reservar por favor llama o escribe a este numero +582129054670',
    'Tiene habitaciones disponible?',
    'Si tenemos, para reservar por favor llama o escribe a este numero +582129054670',
    'Es posible hacer una reservacion para',
    'Si tenemos, para reservar por favor llama o escribe a este numero +582129054670',
    'Tiene habitaciones disponibles el ',
    'Si tenemos, para reservar por favor llama o escribe a este numero +582129054670',
    'Dan desayuno gratis',
    'Si, damos desayunos gratis',
    'las habitaciones incluyen algun beneficio?',
    'Si, incluyen desayunos gratis',
    'Que incluye la habitacion',
    'la habitacion incluye desayuno gratis',
    'Hola, charlie',
    'Hola, como puedo ayudarte?'
    'como se llama el hotel',
    'el hotel se llama rombu',
    'what is the hotel called?',
    'the hotel is called rombu',
    'do you accept pets',
    'Yes, we accept pets'

])

# trainer.train('chatterbot.corpus.english')
trainer.train(
"chatterbot.corpus.english.greetings"
)
# bot = ChatBot(
#     'Math & Time Bot',
#     logic_adapters=[
#         'chatterbot.logic.MathematicalEvaluation',
#         'chatterbot.logic.TimeLogicAdapter'
#     ]
# )

# Get a response to the input text 'I would like to book a flight.'
print('Hola. Soy Charlie, preguntame algo sobre nuestro hotel.')
print( "Hello, I'm charlie. Ask me anything about our hotel")
while True:
    try:
        user_input = input()

        bot_response = chatbot.get_response(user_input)

        print(bot_response)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break